[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parser = { path = "../parser" }
swf = {git = "https://github.com/ruffle-rs/ruffle"}
indexmap = "1.9.1"
